"""primeira migração

Revision ID: d9833f1d149f
Revises: 
Create Date: 2026-05-20 22:05:53.897502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9833f1d149f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('localizacao', sa.String(), nullable=False),
    sa.Column('contato', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('escola',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('localizacao', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('sobrenome', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('aluno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_completo', sa.String(), nullable=False),
    sa.Column('id_colegio', sa.Integer(), nullable=False),
    sa.Column('turma', sa.String(), nullable=False),
    sa.Column('email_aluno', sa.String(), nullable=False),
    sa.Column('senha_aluno', sa.String(), nullable=False),
    sa.Column('contatos', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_colegio'], ['escola.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_aluno'),
    sa.UniqueConstraint('turma')
    )
    op.create_table('funcionario_empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_completo', sa.String(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('email_funcionario', sa.String(), nullable=False),
    sa.Column('senha_funcionario', sa.String(), nullable=False),
    sa.Column('contatos', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_funcionario')
    )
    op.create_table('funcionario_escola',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_completo', sa.String(), nullable=False),
    sa.Column('id_colegio', sa.Integer(), nullable=False),
    sa.Column('email_funcionario', sa.String(), nullable=False),
    sa.Column('senha_funcionario', sa.String(), nullable=False),
    sa.Column('contatos', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_colegio'], ['escola.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_funcionario')
    )
    op.create_table('projetos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('imagem', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('id_aluno', sa.Integer(), nullable=False),
    sa.Column('id_funcionario_escola', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_aluno'], ['aluno.id'], ),
    sa.ForeignKeyConstraint(['id_funcionario_escola'], ['funcionario_escola.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vagas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('id_funcionario', sa.Integer(), nullable=False),
    sa.Column('id_aluno', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_aluno'], ['aluno.id'], ),
    sa.ForeignKeyConstraint(['id_funcionario'], ['funcionario_empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('imagem', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('id_aluno', sa.Integer(), nullable=False),
    sa.Column('id_funcionario_escola', sa.Integer(), nullable=False),
    sa.Column('id_projetos', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_aluno'], ['aluno.id'], ),
    sa.ForeignKeyConstraint(['id_funcionario_escola'], ['funcionario_escola.id'], ),
    sa.ForeignKeyConstraint(['id_projetos'], ['projetos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    op.drop_table('vagas')
    op.drop_table('projetos')
    op.drop_table('funcionario_escola')
    op.drop_table('funcionario_empresa')
    op.drop_table('aluno')
    op.drop_table('usuario')
    op.drop_table('escola')
    op.drop_table('empresa')
    # ### end Alembic commands ###
