"""banco de dados feito, somente trabalhar com ele agora

Revision ID: f13704356903
Revises: 
Create Date: 2026-05-30 21:09:07.185791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f13704356903'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('localizacao', sa.String(length=150), nullable=False),
    sa.Column('contato', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('escola',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('localizacao', sa.String(length=200), nullable=False),
    sa.Column('contato', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.Column('sobrenome', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('senha', sa.String(length=200), nullable=False),
    sa.Column('categoria', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('aluno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('turma', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=100), nullable=False),
    sa.Column('contato', sa.Text(), nullable=False),
    sa.Column('id_colegio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_colegio'], ['escola.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('turma')
    )
    op.create_table('funcionario_empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=100), nullable=False),
    sa.Column('contato', sa.String(length=100), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funcionario_escola',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=100), nullable=False),
    sa.Column('contato', sa.Text(), nullable=False),
    sa.Column('id_colegio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_colegio'], ['escola.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('data_postagem', sa.Date(), nullable=True),
    sa.Column('id_escola', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_escola'], ['escola.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projetos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('data_postagem', sa.Date(), nullable=True),
    sa.Column('imagem', sa.String(), nullable=True),
    sa.Column('id_escola', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_escola'], ['escola.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vagas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('indicacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id_escola', sa.Integer(), nullable=False),
    sa.Column('id_vaga', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_escola'], ['escola.id'], ),
    sa.ForeignKeyConstraint(['id_vaga'], ['vagas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('indicacao')
    op.drop_table('vagas')
    op.drop_table('projetos')
    op.drop_table('post')
    op.drop_table('funcionario_escola')
    op.drop_table('funcionario_empresa')
    op.drop_table('aluno')
    op.drop_table('usuario')
    op.drop_table('escola')
    op.drop_table('empresa')
    # ### end Alembic commands ###
